build:
  version: 2016-03-14 # version of the build schema.
  steps:
    build:
      name: build
      dockerfile: Dockerfile.build
      artifacts:
        - /out
    deployment:
      name: publish
      dockerfile: Dockerfile.publish
      depends_on:
        - build
